In [1]:
import pandas as pds
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
url = 'https://raw.githubusercontent.com/sai1krishna/Assignment/main/Caravan.csv'
csv = pds.read_csv(url,index_col=0,parse_dates=[0])

In [2]:
csv=csv.replace(to_replace="No",value="0")
csv=csv.replace(to_replace="Yes",value="1")
csv

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
1,33,1,3,2,8,0,5,1,3,7,...,0,0,0,1,0,0,0,0,0,0
2,37,1,2,2,8,1,4,1,4,6,...,0,0,0,1,0,0,0,0,0,0
3,37,1,2,2,8,0,4,2,4,3,...,0,0,0,1,0,0,0,0,0,0
4,9,1,3,3,3,2,3,2,4,5,...,0,0,0,1,0,0,0,0,0,0
5,40,1,4,2,10,1,4,1,4,7,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,36,1,1,2,8,0,6,1,2,1,...,0,0,0,1,0,0,0,0,0,0
5819,35,1,4,4,8,1,4,1,4,6,...,0,0,0,1,0,0,0,0,0,0
5820,33,1,3,4,8,0,6,0,3,5,...,0,0,0,1,0,0,0,0,0,1
5821,34,1,3,2,8,0,7,0,2,7,...,0,0,0,0,0,0,0,0,0,0
5822,33,1,3,3,8,0,6,1,2,7,...,0,0,0,0,0,0,0,0,0,0

In [3]:
y_values = csv['Purchase']
x_values = csv.drop(['Purchase'],axis=1)
x_training,x_test,y_training,y_test = train_test_split(x_values, y_values, test_size = 0.2 , random_state = 1)
csv['Purchase'].value_counts()

0    5474
1     348
Name: Purchase, dtype: int64

In [4]:
Logistic_cls = LogisticRegression(solver='liblinear')
Logistic_cls.fit(x_training, y_training)

LogisticRegression(solver='liblinear')

In [5]:
x1_values = Logistic_cls.predict(x_test)
print(x1_values)
print([ a for a in x1_values if a == 1])

['0' '0' '0' ... '0' '0' '0']
[]

In [6]:
Logistic_cls.score(x_test,y_test)

0.9424892703862661